version: "3.2"
services:
  redis:
    image: "redis:alpine"

    # command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"

    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes

    networks:
      node_net:
        ipv4_address: 172.28.1.4
  nats:
    image: nats:2.10.10-alpine
    ports:
      - "4222:4222" # Expose the NATS port
      - "8222:8222"
    # volumes:
    #   - nats-data:/data # Optional persistent data volume
    command:
      - "--jetstream" # Enable Jetstream, NATS' distributed streaming platform (optional)

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
